# Generated by Django 5.1.3 on 2024-12-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_guests_delete_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='user',
        ),
    ]
